name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 22
          cache: npm

      - name: Clone Matterbridge
        run: git clone --depth 1 --single-branch --no-tags -b main https://github.com/Luligu/matterbridge.git ../matterbridge

      - name: Install Matterbridge dependencies
        working-directory: ../matterbridge
        run: npm ci --no-fund --no-audit

      - name: Build Matterbridge
        working-directory: ../matterbridge
        run: npm run build

      - name: Link Matterbridge globally
        working-directory: ../matterbridge
        run: npm link --no-fund --no-audit

      - name: Install dependencies
        run: npm ci --no-fund --no-audit

      - name: Link Matterbridge in project
        run: npm link matterbridge --no-fund --no-audit

      - name: Check formatting
        run: npm run format:check

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Test Vitest with coverage
        run: npm run test:vitest:coverage

      - name: Build
        run: npm run buildProduction
